coreCount : 20
calculateAnew : FALSE
ExpressedGenesOnly : TRUE
fold_change_cutoff : 0.1
FDR_cutoff : 0.01
proteinOnly : TRUE
getFromKG : FALSE
generatePredicateFeatures : TRUE
recalculateNetwork : FALSE
long : FALSE
betweenness_cluster : FALSE
getSNPDataFromWeb : FALSE
delta_bp : 2000000
diffGenesOnly : TRUE
onlySelectNegatives : TRUE
Data.date : "19-06-2019"
