coreCount : 3
calculateAnew : FALSE
fold_change_cutoff : 0.1
FDR_cutoff : 0.01
proteinOnly : TRUE
getFromKG : FALSE
generatePredicateFeatures : FALSE
recalculateNetwork : FALSE
long : FALSE
getSNPDataFromWeb : FALSE
delta_bp : 2000000
diffGenesOnly : FALSE
onlySelectNegatives : TRUE
Data.date : "18-06-2019"
