coreCount : 12
calculateAnew : TRUE
proteinOnly : TRUE
getFromKG : TRUE
saveTriples : TRUE
generatePredicateFeatures : TRUE
recalculateNetwork : TRUE
long : FALSE
getSNPDataFromWeb : TRUE
delta_bp : 2000000
diffGenesOnly : TRUE
onlySelectNegatives : TRUE
Data.date : "2019-06-14"
