coreCount : 20
calculateAnew : FALSE
fold_change_cutoff : 0.1
FDR_cutoff : 0.01
proteinOnly : TRUE
getFromKG : FALSE
generatePredicateFeatures : FALSE
recalculateNetwork : TRUE
long : TRUE
betweenness_cluster : FALSE
getSNPDataFromWeb : FALSE
delta_bp : 2000000
diffGenesOnly : FALSE
onlySelectNegatives : TRUE
Data.date : "19-06-2019"
